{% set version = "2.0.2" %}

package:
  name: cc-plugin-ncei
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cc-plugin-ncei/cc-plugin-ncei-{{ version }}.tar.gz
  sha256: bd84128a197c244b3cc422eed7735d1fb6163371b7c1764fc52a3a06c5297af2

build:
  number: 3
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - compliance-checker >=2.2.0
    - isodate >=0.5.4
    - six >=1.10.0

test:
  imports:
    - cc_plugin_ncei
  commands:
    - compliance-checker --list-tests | grep -q ncei  # [not win]

about:
  home: https://github.com/ioos/cc-plugin-ncei/
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Compliance Checker NCEI Templates Compliance plugin'

extra:
  recipe-maintainers:
    - Bobfrat
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
