{% set version = "2.0.3" %}

package:
  name: cc-plugin-ncei
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cc-plugin-ncei/cc_plugin_ncei-{{ version }}.tar.gz
  sha256: d8f22ce05300d45f63e34e0637e9c6b5bc14e1de6af7aa3e29cff6e81b2875bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - compliance-checker >=2.2.0
    - isodate >=0.5.4
    - six >=1.10.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - cc_plugin_ncei

about:
  home: https://github.com/ioos/cc-plugin-ncei/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Compliance Checker NCEI Templates Compliance plugin'

extra:
  recipe-maintainers:
    - Bobfrat
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
