travis:
  secure:
    BINSTAR_TOKEN: p5iS4cOaFDHdkWGCv9QSiSAFQqxP8BOVoBdF4M+bTxS/dlHak3ZbDPfTDSADBHJeqy/W5agLZvxVEqQ6IifhLjdEyHz/DZ7xJJJjwnkeVR2GrRPKGjhd+983MyFc8SghAIn8Z6FmgFmCwgBQ8ZgmXuEXvOwCwJlwxdwfDK02yiMkzzNcjdSZJaA81eEMJdtl7kQY59QA/yIqvklUF2IZSpuSOlWL5uL62DHzw0F0ALzWCH9Idtwkodn7+mApAjxM8oupqU7f2zqnjVBfxwDKLO9UWGiT3Lb9y65xwm/cujeN7/TAbN55p6RVixggTPD0iFYDXqkeUq2TUxIh9Wp1DJk3dTyLvcgu5mxPkYKdHh+T0mMOcZVrk4E0n21E+wyHBYmlGiK+CD/u/bgTmY9jqKAsrqT/wkcv90RfMJPO4ESy8+bnD9lYmtg/bYWCZLaMYH/EILPAr7l09M96+L3LUaFs3r32hDaKJHA0QQezBp/lDIEjWWQ4yJXeYzsh549qp+LG4lsBGzThUhllg5tFNYi6+55Cut8QyA8zksMHC3RRPtTySk2NeAeFbKrv2jFpINoThS7yKe2uUpzKU9w9hdykgL1cXXXu8ixzJfe8rWjHn1JcIQSh8YbhxjxqZ3BGG6+a6/ibyqHveCEc29LdMP3qpNxKugkLou1iQWbhzPI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
